{{- if .Values.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-lb
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
{{- end }}
