{{- if .Values.headlessService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-headless
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: hazelcast
      port: {{ .Values.headlessService.port }}
      protocol: TCP
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
{{- end }}
